const { urlNormalizer, fetchPage } = require("../utils/utils");

const pages = ["/", "/about", "/services", "/solutions", "/team"];

/* 
  HTTP req -> async
  en caso tal falle el req a una pag (ej. no existe, no tiene info) que se hace? -> Non Blocking
  Debe regresar un objeto estructurado con el contenido de cada pag
  Debe filtrar entre paginas que funcionan y las que no
*/

async function scraper(domain) {
  const baseUrl = urlNormalizer(domain);

  const content = await Promise.allSettled(
    pages.map((page) => fetchPage(baseUrl + page)),
  );

  const fulfilled = content
    .filter((c) => c.status === "fulfilled")
    .map((c) => c.value);

  const combinedText = fulfilled.map((p) => p.text).join(" ");

  return {
    domain: baseUrl,
    pagesScraped: fulfilled.length,
    keyServices: extractKeyServices(combinedText),
    techStack: extractTechStack(combinedText),
    summary: combinedText.slice(0, 500),
    scrapedAt: new Date().toISOString(),
  };
}

function extractKeyServices(text) {
  const servicesKeywords = [
    "Cloud Computing",
    "DevOps Consulting",
    "Software Architecture Design",
    "API Development",
    "Cybersecurity Auditing",
    "Data Engineering",
    "Machine Learning Solutions",
    "QA & Testing",
    "Technical Support",
    "Digital Transformation",
    "IT Project Management",
    "UI/UX Design",
    "Mobile App Development",
    "Database Administration",
    "Business Intelligence",
    "Web Development",
    "Blockchain Development",
    "IoT Solutions",
    "AR/VR Development",
    "Game Development",
    "Embedded Systems",
    "Network Engineering",
    "Systems Integration",
    "ETL Pipeline Development",
    "Data Warehousing",
    "Natural Language Processing",
    "Computer Vision",
    "Robotic Process Automation",
    "Microservices Architecture",
    "Serverless Architecture",
    "Site Reliability Engineering",
    "Platform Engineering",
    "Infrastructure as Code",
    "Continuous Integration/Deployment",
    "Penetration Testing",
    "Vulnerability Assessment",
    "Identity & Access Management",
    "Zero Trust Security",
    "Compliance & Governance",
    "GDPR Consulting",
    "SOC2 Certification",
    "ISO 27001 Consulting",
    "Cloud Migration",
    "Legacy System Modernization",
    "Technical Debt Reduction",
    "Software Licensing Management",
    "Vendor Management",
    "IT Outsourcing",
    "Managed Services",
    "Help Desk Support",
    "NOC Services",
    "Disaster Recovery Planning",
    "Business Continuity Planning",
    "Backup Solutions",
    "Load Balancing",
    "Content Delivery Network Setup",
    "Edge Computing",
    "Quantum Computing Research",
    "High Performance Computing",
    "Distributed Systems Design",
    "Real-Time Data Processing",
    "Streaming Analytics",
    "Data Visualization",
    "Dashboard Development",
    "CRM Development",
    "ERP Integration",
    "SaaS Development",
    "PaaS Solutions",
    "IaaS Management",
    "API Gateway Management",
    "Service Mesh Implementation",
    "Event-Driven Architecture",
    "Message Queue Systems",
    "Search Engine Optimization",
    "Performance Optimization",
    "Accessibility Consulting",
    "Internationalization & Localization",
    "Technical Writing",
    "Developer Relations",
    "Open Source Consulting",
    "Code Review Services",
    "Pair Programming",
    "Agile Coaching",
    "Scrum Implementation",
    "Kanban Consulting",
    "Product Roadmap Planning",
    "User Research",
    "Usability Testing",
    "A/B Testing",
    "Conversion Rate Optimization",
    "Email Automation",
    "Push Notification Systems",
    "Payment Gateway Integration",
    "E-commerce Development",
    "Subscription Billing Systems",
    "Fraud Detection Systems",
    "Recommendation Engines",
    "Chatbot Development",
    "Voice Assistant Development",
    "Sentiment Analysis",
    "Predictive Analytics",
    "Anomaly Detection",
    "MLOps",
    "DataOps",
    "FinOps",
    "AIOps",
    "SecOps",
    "GitOps",
    "NoOps",
    "Digital Twin Development",
    "Simulation Software",
    "CAD/CAM Software Development",
    "Healthcare IT Solutions",
    "Telemedicine Platforms",
    "Electronic Health Records Integration",
    "EdTech Development",
    "LMS Development",
    "AdTech Solutions",
    "MarTech Integration",
    "RegTech Solutions",
    "InsurTech Development",
    "PropTech Solutions",
    "LegalTech Development",
    "Supply Chain Management Software",
    "Logistics Software",
    "Fleet Management Systems",
    "GIS & Mapping Solutions",
    "Geospatial Data Processing",
    "Remote Sensing Applications",
    "Satellite Data Integration",
    "Drone Software Development",
    "Robotics Software",
    "Autonomous Systems Development",
    "SCADA Systems",
    "Industrial IoT",
    "Smart Grid Solutions",
    "Energy Management Software",
    "Environmental Monitoring Systems",
    "Predictive Maintenance",
    "Digital Signage Solutions",
    "Kiosk Software Development",
    "POS System Development",
    "Inventory Management Systems",
    "Warehouse Management Systems",
    "HR Software Development",
    "Payroll Systems",
    "Talent Management Platforms",
    "Learning & Development Platforms",
    "Customer Success Platforms",
    "Customer Data Platforms",
    "Identity Verification Services",
    "KYC/AML Solutions",
    "Biometric Authentication",
    "Multi-Factor Authentication",
    "Single Sign-On Solutions",
    "OAuth Integration",
    "SAML Configuration",
    "GraphQL API Development",
    "REST API Development",
    "SOAP API Integration",
    "Webhook Implementation",
    "WebSocket Development",
    "gRPC Services",
    "Protocol Buffer Design",
    "SDK Development",
    "CLI Tool Development",
    "Browser Extension Development",
    "Desktop Application Development",
    "Cross-Platform Development",
    "Progressive Web App Development",
    "Headless CMS Integration",
    "CMS Development",
    "Portal Development",
    "Community Platform Development",
    "Social Network Development",
    "Live Streaming Platforms",
    "Video on Demand Platforms",
    "Audio Processing Solutions",
    "Image Recognition Systems",
    "OCR Solutions",
    "Document Processing Automation",
    "Contract Lifecycle Management",
    "Digital Signature Integration",
    "Workflow Automation",
    "BPM Solutions",
    "Low-Code Platform Development",
    "No-Code Tool Development",
    "Plugin Development",
    "Theme & Template Development",
    "White-Label Solutions",
    "Multi-Tenant Architecture",
    "Monolith to Microservices Migration",
    "Database Migration",
    "Data Cleansing Services",
    "Master Data Management",
    "Data Governance",
    "Data Catalog Development",
    "Knowledge Graph Development",
    "Semantic Web Solutions",
    "Ontology Design",
    "Federated Learning Systems",
    "Differential Privacy Implementation",
    "Homomorphic Encryption",
    "Blockchain Smart Contracts",
    "DeFi Development",
    "NFT Platforms",
    "Web3 Development",
    "Crypto Exchange Development",
    "Token Development",
    "DAO Tooling",
    "IPFS Integration",
    "Decentralized Identity",
    "Zero-Knowledge Proof Systems",
    "Privacy-Preserving Computation",
  ];
  return servicesKeywords.filter((kw) =>
    text.toLowerCase().includes(kw.toLowerCase()),
  );
}

function extractTechStack(text) {
  const techStackKeywords = [
    "JavaScript",
    "TypeScript",
    "Python",
    "Rust",
    "Go",
    "Java",
    "Kotlin",
    "Swift",
    "C",
    "C++",
    "C#",
    "Ruby",
    "PHP",
    "Scala",
    "Elixir",
    "Erlang",
    "Haskell",
    "Clojure",
    "F#",
    "Dart",
    "R",
    "Julia",
    "Lua",
    "Perl",
    "Groovy",
    "COBOL",
    "Fortran",
    "Assembly",
    "Bash",
    "PowerShell",
    "Solidity",
    "Move",
    "Cadence",
    "React",
    "Angular",
    "Vue.js",
    "Svelte",
    "SolidJS",
    "Qwik",
    "Astro",
    "Remix",
    "Next.js",
    "Nuxt.js",
    "Gatsby",
    "Eleventy",
    "SvelteKit",
    "SolidStart",
    "Ember.js",
    "Backbone.js",
    "Alpine.js",
    "Lit",
    "Preact",
    "Inferno",
    "Node.js",
    "Deno",
    "Bun",
    "Express",
    "Fastify",
    "Koa",
    "Hapi",
    "NestJS",
    "AdonisJS",
    "Sails.js",
    "Feathers.js",
    "Meteor",
    "Loopback",
    "Moleculer",
    "Hono",
    "Elysia",
    "Nitro",
    "tRPC",
    "GraphQL",
    "REST",
    "gRPC",
    "WebSockets",
    "Django",
    "Flask",
    "FastAPI",
    "Tornado",
    "Sanic",
    "Falcon",
    "Pyramid",
    "Starlette",
    "Litestar",
    "Bottle",
    "CherryPy",
    "Quart",
    "Spring Boot",
    "Spring Cloud",
    "Micronaut",
    "Quarkus",
    "Helidon",
    "Vert.x",
    "Play Framework",
    "Lagom",
    "Dropwizard",
    "Grails",
    "Javalin",
    "Spark Java",
    "Laravel",
    "Symfony",
    "CodeIgniter",
    "CakePHP",
    "Yii",
    "Phalcon",
    "Slim",
    "Lumen",
    "Livewire",
    "Inertia.js",
    "Ruby on Rails",
    "Sinatra",
    "Hanami",
    "ASP.NET Core",
    "ASP.NET MVC",
    "Blazor",
    "Razor Pages",
    "MAUI",
    "Gin",
    "Echo",
    "Fiber",
    "Chi",
    "Gorilla Mux",
    "Buffalo",
    "Actix-Web",
    "Axum",
    "Rocket",
    "Warp",
    "Tide",
    "Ktor",
    "Exposed",
    "Vapor",
    "Perfect",
    "Kitura",
    "Phoenix",
    "Plug",
    "Absinthe",
    "PostgreSQL",
    "MySQL",
    "MariaDB",
    "SQLite",
    "SQL Server",
    "Oracle DB",
    "MongoDB",
    "CouchDB",
    "DynamoDB",
    "Cosmos DB",
    "Firestore",
    "FaunaDB",
    "Cassandra",
    "ScyllaDB",
    "HBase",
    "Bigtable",
    "Redis",
    "Memcached",
    "Hazelcast",
    "Apache Ignite",
    "Elasticsearch",
    "OpenSearch",
    "Solr",
    "Meilisearch",
    "Typesense",
    "ClickHouse",
    "TimescaleDB",
    "InfluxDB",
    "QuestDB",
    "TDengine",
    "Snowflake",
    "BigQuery",
    "Redshift",
    "Synapse",
    "Databricks",
    "Neo4j",
    "ArangoDB",
    "TigerGraph",
    "Amazon Neptune",
    "PlanetScale",
    "Neon",
    "CockroachDB",
    "TiDB",
    "YugabyteDB",
    "DuckDB",
    "Dolt",
    "SurrealDB",
    "EdgeDB",
    "Dgraph",
    "Prisma",
    "TypeORM",
    "Sequelize",
    "Mongoose",
    "Drizzle",
    "SQLAlchemy",
    "Tortoise ORM",
    "Peewee",
    "Diesel",
    "SeaORM",
    "Hibernate",
    "JPA",
    "JDBI",
    "MyBatis",
    "jOOQ",
    "Entity Framework",
    "Dapper",
    "NHibernate",
    "ActiveRecord",
    "Sequel",
    "ROM",
    "Docker",
    "Podman",
    "Kubernetes",
    "Helm",
    "Rancher",
    "OpenShift",
    "Docker Compose",
    "Docker Swarm",
    "Nomad",
    "Mesos",
    "Terraform",
    "Pulumi",
    "Ansible",
    "Chef",
    "Puppet",
    "SaltStack",
    "AWS CDK",
    "Bicep",
    "CloudFormation",
    "Crossplane",
    "ArgoCD",
    "FluxCD",
    "Tekton",
    "Spinnaker",
    "Jenkins",
    "GitHub Actions",
    "GitLab CI",
    "CircleCI",
    "Travis CI",
    "Buildkite",
    "AWS Lambda",
    "Azure Functions",
    "Google Cloud Functions",
    "Cloudflare Workers",
    "Vercel",
    "Netlify",
    "Render",
    "Railway",
    "Fly.io",
    "Heroku",
    "AWS",
    "Azure",
    "Google Cloud",
    "DigitalOcean",
    "Linode",
    "Vultr",
    "Hetzner",
    "NGINX",
    "Apache",
    "Caddy",
    "HAProxy",
    "Traefik",
    "Istio",
    "Linkerd",
    "Consul",
    "Envoy",
    "Cilium",
    "Prometheus",
    "Grafana",
    "Datadog",
    "New Relic",
    "Dynatrace",
    "Jaeger",
    "Zipkin",
    "OpenTelemetry",
    "Honeycomb",
    "Sentry",
    "Apache Kafka",
    "RabbitMQ",
    "Apache Pulsar",
    "NATS",
    "ActiveMQ",
    "ZeroMQ",
    "Apache Spark",
    "Apache Flink",
    "Apache Storm",
    "Apache Beam",
    "Apache Hadoop",
    "Apache Hive",
    "Apache Airflow",
    "Apache Superset",
    "dbt",
    "Dagster",
    "Prefect",
    "Luigi",
    "Mage",
    "Airbyte",
    "Fivetran",
    "Looker",
    "Metabase",
    "Tableau",
    "Power BI",
    "Grafana",
    "Redash",
    "TensorFlow",
    "PyTorch",
    "Keras",
    "scikit-learn",
    "XGBoost",
    "LightGBM",
    "Hugging Face",
    "LangChain",
    "LlamaIndex",
    "AutoGen",
    "CrewAI",
    "Semantic Kernel",
    "Ollama",
    "vLLM",
    "BentoML",
    "Seldon",
    "MLflow",
    "DVC",
    "Weights & Biases",
    "Kubeflow",
    "ZenML",
    "Metaflow",
    "SageMaker",
    "Vertex AI",
    "Azure ML",
    "Ray",
    "Triton",
    "Pinecone",
    "Weaviate",
    "Qdrant",
    "Chroma",
    "Milvus",
    "pgvector",
    "NumPy",
    "Pandas",
    "Polars",
    "Dask",
    "Vaex",
    "PySpark",
    "React Native",
    "Flutter",
    "Ionic",
    "Xamarin",
    "Capacitor",
    "Expo",
    "SwiftUI",
    "UIKit",
    "Jetpack Compose",
    "Android SDK",
    "Unity",
    "Unreal Engine",
    "Godot",
    "Babylon.js",
    "Three.js",
    "PlayCanvas",
    "WebGL",
    "WebGPU",
    "WebAssembly",
    "WebRTC",
    "WebXR",
    "Tailwind CSS",
    "Bootstrap",
    "Material UI",
    "Chakra UI",
    "Ant Design",
    "Shadcn UI",
    "Radix UI",
    "Headless UI",
    "Mantine",
    "DaisyUI",
    "Sass",
    "LESS",
    "Styled Components",
    "Emotion",
    "CSS Modules",
    "Webpack",
    "Vite",
    "Rollup",
    "Parcel",
    "esbuild",
    "Turbopack",
    "Babel",
    "SWC",
    "ESLint",
    "Prettier",
    "Biome",
    "Jest",
    "Vitest",
    "Mocha",
    "Jasmine",
    "Cypress",
    "Playwright",
    "Selenium",
    "Puppeteer",
    "Testing Library",
    "Storybook",
    "Redux",
    "Zustand",
    "Jotai",
    "Recoil",
    "MobX",
    "XState",
    "Pinia",
    "NgRx",
    "React Query",
    "SWR",
    "Apollo Client",
    "Relay",
    "urql",
    "Axios",
    "Fetch API",
    "ky",
    "got",
    "superagent",
    "Socket.io",
    "ws",
    "uWebSockets",
    "Pusher",
    "Ably",
    "Stripe",
    "Braintree",
    "PayPal SDK",
    "Square SDK",
    "Adyen",
    "Twilio",
    "SendGrid",
    "Mailgun",
    "Postmark",
    "Resend",
    "Auth0",
    "Clerk",
    "NextAuth.js",
    "Passport.js",
    "Keycloak",
    "Okta",
    "Firebase Auth",
    "Supabase Auth",
    "AWS Cognito",
    "Firebase",
    "Supabase",
    "Appwrite",
    "Nhost",
    "Pocketbase",
    "Contentful",
    "Sanity",
    "Strapi",
    "Directus",
    "Payload CMS",
    "Prismic",
    "Ghost",
    "WordPress",
    "Drupal",
    "Joomla",
    "Shopify",
    "Magento",
    "WooCommerce",
    "BigCommerce",
    "Medusa",
    "Elasticsearch",
    "Algolia",
    "Typesense",
    "MeiliSearch",
    "Cloudinary",
    "ImageKit",
    "AWS S3",
    "Backblaze B2",
    "Uploadthing",
    "Hardhat",
    "Foundry",
    "Truffle",
    "Anchor",
    "Brownie",
    "Ethers.js",
    "Web3.js",
    "Wagmi",
    "Viem",
    "RainbowKit",
    "IPFS",
    "Arweave",
    "Filecoin",
    "The Graph",
    "Chainlink",
    "Git",
    "GitHub",
    "GitLab",
    "Bitbucket",
    "Jira",
    "Linear",
    "Notion",
  ];
  return techStackKeywords.filter((kw) =>
    text.toLowerCase().includes(kw.toLowerCase()),
  );
}

module.exports = scraper;
